In [1]:
import warnings
warnings.filterwarnings('ignore')
from IPython.display import Image
import numpy as np

def pprint(arr):
    print('type: {}'.format(type(arr)))
    print('shape: {}, dimension: {}, dtype: {}'.format(arr.shape, arr.ndim, arr.dtype))
    print('numpy 배열에 저장된 데이터\n', arr)

인덱싱

In [ ]:
# 배열의 각 요소는 axis 인덱스로 참조할 수 있다.
# 1차원 배열은 1개의 인덱스, 2차원 배열은 2개의 인덱스, 3차원 배열은 3개의 인덱스 요소로 참조할 수 있다.
# 인덱싱 작업시[행][열]과 같은 인덱스를 지정하거나 [행, 열]과 같이 인덱스를 지정할 수 있다.

In [5]:
# 1차원 배열
a = np.arange(24)
pprint(a)
# 1차원 배열 요소 참조 및 변경
print(a[5])
a[0] = 10000
pprint(a)

type: <class 'numpy.ndarray'>
shape: (24,), dimension: 1, dtype: int32
numpy 배열에 저장된 데이터
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
5
type: <class 'numpy.ndarray'>
shape: (24,), dimension: 1, dtype: int32
numpy 배열에 저장된 데이터
 [10000     1     2     3     4     5     6     7     8     9    10    11
    12    13    14    15    16    17    18    19    20    21    22    23]


In [12]:
# 2차원 배열
a = np.arange(24).reshape(4, 6)
pprint(a)
# 2차원 배열 요소 참조 및 변경
print(a[2][3])
print(a[2,3])
a[1][2] = 10000
a[2,4] = 20000
pprint(a)

type: <class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
15
15
type: <class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[    0     1     2     3     4     5]
 [    6     7 10000     9    10    11]
 [   12    13    14    15 20000    17]
 [   18    19    20    21    22    23]]


In [15]:
# 3차원 배열
a = np.arange(24).reshape(2, 4, 3)
pprint(a)
# 3차원 배열 요소 참조 및 변경
print(a[1][3][0])
print(a[1,3,0])
a[0][2][2] = 10000
a[1,3,0] = 20000
pprint(a)

type: <class 'numpy.ndarray'>
shape: (2, 4, 3), dimension: 3, dtype: int32
numpy 배열에 저장된 데이터
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
21
21
type: <class 'numpy.ndarray'>
shape: (2, 4, 3), dimension: 3, dtype: int32
numpy 배열에 저장된 데이터
 [[[    0     1     2]
  [    3     4     5]
  [    6     7 10000]
  [    9    10    11]]

 [[   12    13    14]
  [   15    16    17]
  [   18    19    20]
  [20000    22    23]]]


슬라이싱

In [21]:
# 1차원 배열 슬라이싱
a = np.arange(24)
print(a)
print(a[2:6])
print(a[:6])
print(a[2:])
print(a[:])
print(a[::2])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[2 3 4 5]
[0 1 2 3 4 5]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  2  4  6  8 10 12 14 16 18 20 22]
